exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('users')
    .del()
    .then(() =>
    // Inserts seed entries
      knex('users').insert([
        {
          id: 1,
          role_id: 1,
          email: 'guest@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstGuest',
          last_name: 'LastGuest',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          role_id: 1,
          email: 'guest2@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstGuest2',
          last_name: 'LastGuest2',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          role_id: 2,
          email: 'service@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstService',
          last_name: 'LastService',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          role_id: 3,
          email: 'receptionist@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstReceptionist',
          last_name: 'LastReceptionist',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          role_id: 4,
          email: 'accountant@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstAccountant',
          last_name: 'LastAccountant',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          role_id: 5,
          email: 'hr@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstHr',
          last_name: 'LastHr',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          role_id: 6,
          email: 'admin@gmail.com',
          active: 1,
          password: '$2a$10$45pS3BzG2dwPJd/kMurNp.QcmOxTXPHp6qAnS7otE7r3UOvSUo0Cu',
          first_name: 'FirstAdmin',
          last_name: 'LastAdmin',
          phone: '08022835496',
          address: '10 Ayoola Balogun Street, Ikeja GRA',
          city: 'Ikeja',
          state: 'Lagos',
          postal_code: '23401',
          country: 'Nigeria',
          profile_picture: 'defaultprofile.jpg',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ]));
};
